### ISSUE TITLE
Fails due to usupported docker-compose version

### ISSUE THREAD

**Issue by dvdjaco** [ebbba-org/ansible-role-scalelite#7]
*Steps to reproduce* - Run the playbook on a Ubuntu 16.04 TLS server

*Result* - ansible-playbook fails on task `[scalelite : Tear down existing services]` with the following error msg:

> Configuration error - Version in "/root/scalelite-run/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

 The module community.docker.docker_compose only supports compose versions 1 and 2. The docker-compose.yml file we get from https://github.com/ebbba-org/scalelite-run.git declares `version: '3'`

**Comment by BrutalBirdie** [comment]
Sorry I just seen this issue now.
Ubuntu 16.04 is no longer supported, please use Ubuntu 18.04 LTS or preferred Ubuntu 20.04 LTS
